spring.application.name=ATM
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/atm_db
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dailect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
